---
apiVersion: v1
kind: Service
metadata:
  name: hellokyan
spec:
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
  selector:
    app: hellokyan
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokyan
spec:
  selector:
    matchLabels:
      app: hellokyan
  template:
    metadata:
      labels:
        app: hellokyan
    spec:
      containers:
      - name: hellokyan
        image: nicklinnell/hellokyan:staging
        ports:
        - containerPort: 3000
