name: Publish Docker image
on: 
  pull_request:
    types: [open, reopened, synchronize]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set env variables
        run: |
          export APP_ID=pr-${{ github.event.number }}
          echo "APP_ID=$APP_ID" >> $GITHUB_ENV

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nicklinnell/hellokyan
          tags: ${{ env.APP_ID }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
           key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
           name: id_rsa # optional
           known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - run: |
          git clone git@github.com:nicklinnell/review-apps.git
          git config --global user.email "nick@kyan.com"
          git config --global user.name "nicklinnell"
          cd review-apps
          cat preview.yaml | kyml tmpl -e ${{ env.APP_IP }} | tee helm/${{ env.APP_ID }}.yaml
          git add .
          git commit -m "Adding PR ${{ github.event.number }} from ${{ github.repository }}"
          git push origin master
