name: Publish Docker image
on: 
  pull_request:
    types: [open, reopened, synchronize]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set env variables
        run: |
          export APP_ID=pr-${{ github.event.number }}
          echo "APP_ID=$APP_ID" >> $GITHUB_ENV

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nicklinnell/hellokyan
          tags: ${{ env.APP_ID }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
           key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
           name: id_rsa # optional
           known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - run: |
          git clone git@github.com:nicklinnell/review-apps.git
          git config --global user.email "nick@kyan.com"
          git config --global user.name "nicklinnell"
          cd review-apps
          cat preview.yaml | kyml tmpl -e ${{ env.APP_IP }} | tee helm/${{ env.APP_ID }}.yaml
          git add .
          git commit -m "Adding PR ${{ github.event.number }} from ${{ github.repository }}"
          git push origin master

      # - name: Checkout review apps repo
      #   uses: actions/checkout@v2
      #   with:
      #     repository: nicklinnell/review-apps
      #     path: review-apps

      # - name: Define preview environment app
      #   run: |

      # - name: Push to review apps repo
      #   uses: actions-x/commit@v2
      #   with:
      #     email: 'nick@kyan.com'
      #     name: 'nicklinnell'
      #     branch: master
      #     files: review-apps
      #     repository: https://nicklinnell:${{ secrets.API_TOKEN_GITHUB }}@github.com/nicklinnell/review-apps.git
      #     message: "Adding PR ${{ github.event.number }} from ${{ github.repository }}"
      #     token: ${{ secrets.API_TOKEN_GITHUB }}
      #     force: true

      # - name: Pushes to another repository
      #   uses: nicklinnell/push-to-repo@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source-directory: review-apps
      #     destination-github-username: nicklinnell
      #     destination-repository-username: nicklinnell
      #     destination-repository-name: review-apps
      #     user-email: nick@kyan.com
      #     target_branch: master
      #     commit-message: "Adding PR ${{ github.event.number }} from ${{ github.repository }}"

      # - name: Push to review apps repo
      #   uses: x-actions/gh-pages@release/v1
      #   env:
      #     GITHUB_EMAIL: "nick@kyan.com"
      #     GITHUB_USERNAME: "nicklinnell"
      #     PUBLISH_REPO: git@github.com:nicklinnell/review-apps.git
      #     PUBLISH_BRANCH: master
      #     PUBLISH_DIR: ./review-apps
      #     DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
