name: Publish Docker image
on: 
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.API_TOKEN_GITHUB }}'
      - run: 'Triggered deployment'
        if: steps.check.outputs.triggered == 'true'

      - uses: docker/setup-buildx-action@v1
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set env variables
        run: |
          export TAG_ID=pr-${{ github.event.number }}
          echo "TAG_ID=$TAG_ID" >> $GITHUB_ENV
          export APP_ID=pr-${{ github.event.repository.name }}-${{ github.event.number }}
          echo "APP_ID=$APP_ID" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: nicklinnell/hellokyan:${{ env.APP_ID }}
          push: true

      - name: Install kyml
        run: |
          sudo curl -sfL -o /usr/local/bin/kyml https://github.com/frigus02/kyml/releases/download/v20190906/kyml_20190906_linux_amd64
          sudo chmod +x /usr/local/bin/kyml

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
           key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
           name: id_rsa # optional
           known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - run: |
          git clone git@github.com:nicklinnell/review-apps.git
          git config --global user.email "nick@kyan.com"
          git config --global user.name "nicklinnell"
          cd review-apps
          cat ../helm/preview.yaml | kyml tmpl -e APP_ID -e TAG_ID | tee helm/templates/"${{ env.APP_ID }}".yaml
          git add .
          git diff-index --quiet HEAD || git commit -m "Adding PR ${{ github.event.number }} from ${{ github.repository }}"
          git push origin master

      - name: Create DNS record
        uses: nicklinnell/dnsimple-create-record@v1
        with:
          name: ${{ env.APP_ID }}
          type: "A"
          content: "192.168.1.1"
          token: ${{ secrets.DNSIMPLE_TOKEN }}
          zone: ${{ secrets.DNSIMPLE_ZONE }}
          account: ${{ secrets.DNSIMPLE_ACCOUNT }}
